# Site settings
title: Strona Piotra Morawskiego
email: pmorawski55@wp.pl
description: > # this means to ignore newlines until "baseurl:"
  PiÄ™kny opis mojej stronki na zdalne praktyki w ZSE.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "2137" # the base hostname & protocol for your site
twitter_username: andrzejduda
github_username:  pmorawski55

# Build settings
markdown: kramdown
